// gasModel.js
//
// The equation-of-state layer for section 11-12 of the doc: the gas
// trapped inside a hollow ball (tennis ball, basketball, etc). Pure
// functions only, same discipline as contactModel.js — no state, no
// integration, no knowledge of the solver's timestep.
//
// Ideal gas law:  P V = n R T
// We hold n (amount of gas) and T (temperature) fixed for this demo
// — no thermodynamics yet, see file note at bottom — so as the ball
// deforms and its internal volume V drops, pressure P rises
// according to:
//
//     P = (n R T) / V = P0 * (V0 / V)
//
// which is just the isothermal form of the ideal gas law referenced
// to a starting pressure/volume. That extra pressure above ambient
// pushes outward on the shell and adds to the normal contact force,
// exactly like the doc's causal chain:
//
//   rubber shell deforms -> internal volume decreases ->
//   gas pressure increases -> pressure pushes shell outward ->
//   ball rebounds

const AMBIENT_PRESSURE_PA = 101325; // 1 atm, for reference/clamping

// Approximate internal volume of the ball as a sphere minus the
// volume "swallowed" by contact penetration (a spherical cap). This
// is a simplification — a real deforming shell doesn't lose volume
// as a clean spherical cap — but it's the right order of behavior:
// volume strictly decreases as penetration increases, and returns to
// V0 with zero penetration.
export function currentInternalVolume({ ballRadiusM, penetrationM }) {
  const R = ballRadiusM;
  const fullVolume = (4 / 3) * Math.PI * R ** 3;
  if (penetrationM <= 0) return fullVolume;

  // Spherical cap volume: h = penetration depth (capped at 2R)
  const h = Math.min(penetrationM, 2 * R);
  const capVolume = ((Math.PI * h * h) / 3) * (3 * R - h);
  return Math.max(fullVolume - capVolume, fullVolume * 0.05); // floor so V never hits 0 (P would blow up)
}

// P = P0 * (V0 / V) — isothermal ideal gas response to a volume change.
export function gasPressure({ initialPressurePa, initialVolumeM3, currentVolumeM3 }) {
  if (currentVolumeM3 <= 0) return Infinity;
  return initialPressurePa * (initialVolumeM3 / currentVolumeM3);
}

// Converts the pressure differential (internal - ambient) into an
// outward force on the contact patch, so it can be added directly
// to normalContactForce()'s output in the solver. Only the
// *overpressure* does mechanical work pushing back against the
// ground; ambient pressure is already balanced out on all sides.
export function gasOverpressureForce({ internalPressurePa, contactAreaM2 }) {
  const overpressure = Math.max(internalPressurePa - AMBIENT_PRESSURE_PA, 0);
  return overpressure * contactAreaM2;
}

export { AMBIENT_PRESSURE_PA };

// --- What's still not built (per the doc) -----------------------
// - Temperature is held constant: no heat generated by viscous
//   dissipation (section 8/18 dampingCoeff) feeding back into T,
//   which would need real thermodynamics (heat capacity, some
//   simple heat-transfer/cooling model to ambient).
// - Fracture (section 9) isn't implemented at all: no stress-based
//   failure criterion, no state for "this ball is now popped/torn".
//   That needs a decision about what should happen in the sim when
//   it triggers (remove the ball? spawn debris? just stop applying
//   gas overpressure?) before it's worth writing.
